In [ ]:
install.packages("sqldf")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘plogr’, ‘gsubfn’, ‘proto’, ‘RSQLite’, ‘chron’

In [ ]:
# Create vectors for different columns
ids <- c(1, 2, 3, 4, 5)
names <- c("Alice", "Bob", "Charlie", "David", "Eve")
years_of_exp <- c(5, 8, 3, 10, 6)
roles <- c("Engineer", "Manager", "Analyst", "Director", "Developer")

# Create a dataframe
df <- data.frame(
  id = ids,
  name = names,
  year_of_exp = years_of_exp,
  role = roles,
  stringsAsFactors = FALSE  # Prevent strings from being converted to factors
)
df

  id name    year_of_exp role
1 1  Alice    5          Engineer
2 2  Bob      8          Manager
3 3  Charlie  3          Analyst
4 4  David   10          Director
5 5  Eve      6          Developer

In [ ]:
library(sqldf)

result <- sqldf("SELECT * FROM df WHERE year_of_exp > 5")
result

  id name  year_of_exp role
1 2  Bob    8          Manager
2 4  David 10          Director
3 5  Eve    6          Developer

In [ ]:
library(sqldf)

result <- sqldf("SELECT * FROM df ORDER BY year_of_exp DESC")
result

  id name    year_of_exp role
1 4  David   10          Director
2 2  Bob      8          Manager
3 5  Eve      6          Developer
4 1  Alice    5          Engineer
5 3  Charlie  3          Analyst

In [ ]:
library(sqldf)

result <- sqldf("SELECT AVG(year_of_exp) AS avg_exp FROM df")
result

  avg_exp
1 6.4

In [ ]:
library(sqldf)

df2 <- data.frame(id = c(1, 2, 3, 4, 5),
                  salary = c(50000, 60000, 70000, 80000, 90000)
                  )

result <- sqldf("SELECT df.*, df2.salary FROM df LEFT JOIN df2 ON df.id = df2.id")
result

  id name    year_of_exp role      salary
1 1  Alice    5          Engineer  50000
2 2  Bob      8          Manager   60000
3 3  Charlie  3          Analyst   70000
4 4  David   10          Director  80000
5 5  Eve      6          Developer 90000

In [ ]:
library(sqldf)

result <- sqldf("SELECT role, AVG(year_of_exp) AS avg_exp FROM df GROUP BY role")
result

  role      avg_exp
1 Analyst    3
2 Developer  6
3 Director  10
4 Engineer   5
5 Manager    8

In [ ]:
library(sqldf)

result <- sqldf("SELECT *,
                CASE WHEN id = 1
                     THEN year_of_exp + 1
                     ELSE year_of_exp
                END AS year_of_exp
                FROM df")
result

  id name    year_of_exp role      year_of_exp
1 1  Alice    5          Engineer   6
2 2  Bob      8          Manager    8
3 3  Charlie  3          Analyst    3
4 4  David   10          Director  10
5 5  Eve      6          Developer  6

In [ ]:
library(sqldf)

result <- sqldf("SELECT * FROM df WHERE year_of_exp <= 5")
result

  id name    year_of_exp role
1 1  Alice   5           Engineer
2 3  Charlie 3           Analyst

In [ ]:
library(sqldf)

result <- sqldf("SELECT id, name FROM df")
result

  id name
1 1  Alice
2 2  Bob
3 3  Charlie
4 4  David
5 5  Eve